name: CI/CD Pipeline

on:
  push:
    branches:
      - master  #Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build with Gradle
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

        env:
          USERNAME: ${{ secrets.USERNAME_GITHUB }}
          TOKEN: ${{ secrets.TOKEN_GITHUB }}

      # Step 4: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}




      # Step 6: Define the VERSION environment variable
      - name: Set version
        run: echo "VERSION=3" >> $GITHUB_ENV

        # Step 7: Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/video-service1:${{ env.VERSION }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/video-service1:${{ env.VERSION }}
      

      #      # Step 6: Build and push Docker image saidalo
      #      - name: Build and push Docker image
      #        run: |
      #          docker build -t ${{ secrets.DOCKER_USERNAME }}/channel-service:latest .
      #          docker push ${{ secrets.DOCKER_USERNAME }}/channel-service:latest




